### PR TITLE
Add function db-uri that takes any database connection-uri.

### PR DESCRIPTION
**Pull request by pupeno**
Based on the protocol specified in connection-uri, it’ll call the appropriate helper functions to add nice defaults, like the back tick for quoting in MySQL. It still accepts extra options, like :make-pool?. Tests included but not exhaustive.

I can write more tests if you feel it's needed. If you are happy with this change, I'll go and fix the documentation of db-uri and the other helper functions to account for connection-uri.

### CODE REVIEW

**Comment by immoh** [comment]
I don't want to add new public function to the API, as discussed before the API should look like this:

```clj
(defdb mydb {:connection-uri ...})
```
Also, I don't think it should throw if the db is not recognized, it still could be valid JDBC connection.

**Comment by pupeno** [comment]
Well, my idea is that you can call (defdb mydb {:connection-uri ...}) when you really want to construct the connection hashmap and (db-uri ...) when you want to *automatically enhance it*. Otherwise, there's no way of connecting to mysql, for example, without specifying the quote function and someone might want to connect to it without specifying it, don't you think?

**Comment by pupeno** [comment]
I do agree that db-uri is not a good name, but I couldn't think of any others.

**Comment by pupeno** [comment]
I was looking at implementing this without the db-uri function and it seems like it should be implemented in the create-db function, but create-db sometimes gets the result of having called mysql/postgres/etc, so, if I dispatch on the uri and call mysql/postgres/etc I would be calling it a second time. Do you think that would be an issue?

**Comment by pupeno** [comment]
I made two more branches. In this one: 

https://github.com/korma/Korma/compare/master...pupeno:database-uri-implicitly-enhancing-specs?expand=1 

I removed db-uri so create-db will call a function to enhance the spec by calling the appropriate protocol based on connection-uri.

In this one:

https://github.com/korma/Korma/compare/master...pupeno:database-uri-implicitly-enhancing-specs-with-tagging?expand=1

I tag the spec with the appropriate protocol and take the tag, a key :protocol, as a sign that the spec shouldn't be further enhanced.

What do you think? So far all options seem messy to me in one way or another, but I can't find a clean solution that maintains the current API untouched.

**Comment by ls4f** [comment]
The helper functions could attach metadata to what they return, so the map itself isn't polluted and you still know if it was passed directly or not.

**Comment by immoh** [comment]
I think the default should be that we set the correct classname and delimiters, just like when using the helper functions directly. I can’t think of any use case where user wouldn't want that but they can always override keys by giving new values in the spec map if they need to.

Calling helper function twice is a problem. I think it would be best to revert the changes from the previous PR and modify `connection-pool` to work with both jdbc uri and subprotocol/subname. That way we can set correct parameters (enhance) in `create-db` if we get :connection-uri. We probably shouldn’t call helper functions directly cause we don’t want all the functionality from them (shoudn’t set subprotocol and subname for example). 

The other reason why I’m suggesting to revert is that you can't configure db anymore by giving subprotocol and subname directly without using helper functions because `connection-pool` now expects uri. Unfortunately there are no tests for it so the build didn’t break. 

I admit that it is still not as clean as I would like to but I think it will be better for the users if they don't have to add extra `db-uri`when configuring using connection uri.

Does it make any sense?

**Comment by pupeno** [comment]
Is `connection-pool` called when you have `:make-pool?` false?

If `connection-pool` is the one building uris, does it mean that the helper functions either get a uri or they get a protocol/host/db/etc and add the other attributes?

I'm a bit confused about which functions do what.

**Comment by immoh** [comment]
`connection-pool` is not called if `:make-pool?` is false. In that case the spec is passed directly to clojure.java.jdbc and that's why whatever we decide to use needs to be supported by clojure.java.jdbc.

The only reason Korma currently builds uri is that c3p0 (connection pool lib) requires it.

**Comment by pupeno** [comment]
So the connection-uri will work out of the way when not using a pool?

**Comment by pupeno** [comment]
Is this what you mean: https://github.com/korma/Korma/pull/319

**Comment by immoh** [comment]
Yes. 

I was also thinking that helper functions wouldn't need to have any logic based on uri. As I see it helper functions have 3 different purposes:

1. Set classname, subprotocol and construct subname
2. Replace missing values (e.g. hostname, port) with vendor specific default values
3. Set delimiters

Only 3 is relevant for connection uri case so it would probably make sense to refactor it out from helper functions so that it can reused in when connection uri is given.

**Comment by immoh** [comment]
Connection uri will work without pooling, as long as we are using same keyword as clojure.java.jdbc.

**Comment by pupeno** [comment]
If the helper functions do not have logic based on URIs, calling (mysql {:connection-uri "jdbc:mysql://somehost/blahblah"}) will result in having a hashmap with conflicting connection-uri and subname, which neither you nor I wanted, did you revert to wanting that?

**Comment by immoh** [comment]
I didn't revert. Korma shouldn't mix them internally and should discourage users from mixing them as well. Users can still give conflicting keys (raw-map `{:connection-uri "jdbc:mysql://blah" :subprotocol "oracle"}` or helper function `(oracle {:connection-uri "jdbc:mysql://blah"})`) but there's very little we can do about it unless we start validating input and I don't want that at this point.

**Comment by pupeno** [comment]
Mixing what? I'm confused.

Do you want 

```clojure
(mysql {:connection-uri "jdbc:mysql://somehost/blahblah"})
```

to generate

```clojure
{:connection-uri "jdbc:mysql://somehost/blahblah"
 :classname "com.mysql.jdbc.Driver"
 :delimiters "`"
 :make-pool? false}
```

or to generate:

```clojure
{:subprotocol "mysql"
 :subname "//localhost:3306/"  ; WRONG subname
 :connection-uri "jdbc:mysql://somehost/blahblah"
 :classname "com.mysql.jdbc.Driver"
 :delimiters "`"
 :make-pool? false}
```

I think the second one is confusing to people that might be debugging an application but by now I don't care, I just want to be able to use Korma in Heroku.

**Comment by immoh** [comment]
```clj
(mysql {:connection-uri "jdbc:mysql://somehost/blahblah"})
```

shouldn't be used so it doesn't really matter what it generates.

**Comment by pupeno** [comment]
So, if I have a connection URI, how do I connect to the database getting the correct delimiter?

**Comment by immoh** [comment]
Perhaps I wasn't able to express myself clearly. Let the code speak for itself:

https://github.com/korma/Korma/compare/connection_uri_support

**Comment by ls4f** [comment]
Loving the concept of having actual logic in a single spot

**Comment by immoh** [comment]
Thanks, I'm quite satisfied with the end result. 

@pupeno Is this usable for Luminus or is there still something to address?

**Comment by pupeno** [comment]
That seems to be ok.

**Comment by immoh** [comment]
Connection uri support implemented in 527565de9eb44a64a5ed88f77f3a97122d0a35db

**Pull request closed without merging**
