### PR TITLE
Support also other subqueries than just subselect.

### PR DESCRIPTION
**Pull request by juhovh**
Subselect works quite fine, but I need to be able to select from union results. I haven't written tests for the patch yet, because I want to make sure that it's ok first, but to me it feels pretty straightforward.

### CODE REVIEW

**Comment by immoh** [comment]
Why `subselect` wouldn't work here?

```clj
(sql-only (select (subselect (union (queries (subselect :users1 (where {:id [<= 10]}))
                                             (subselect :users2 (where {:id [> 10]})))))
                  (fields :id)))
=> "SELECT \"id\" FROM ((SELECT \"users1\".* FROM \"users1\" WHERE (\"users1\".\"id\" <= ?)) UNION (SELECT \"users2\".* FROM \"users2\" WHERE (\"users2\".\"id\" > ?)))"
```

**Comment by juhovh** [comment]
Sorry, forgot to reply to this.

You're probably right that subselect works here, wasn't aware of it and it's not quite documented. Also I find it extremely confusing and somewhat semantically incorrect to have 4 selects in Clojure query resulting in just 3 selects in the final SQL. Feel free to disagree, but it makes me feel really dirty. :)

Nevertheless, I'll keep my macro in my own code to result in more readable queries, "select subselect union queries subselect" is a bit too much of select to me.

**Comment by immoh** [comment]
I agree that it is awkward and dirty, but I just don't think "select subquery union queries subselect" is that much better.

Ultimately it boils down to the fact that `select`, `union` etc. do two things: create they query and execute it against db. This makes composition awkward and makes creating more complicated queries difficult.

**Comment by juhovh** [comment]
Closing this, since subselect works.

**Pull request closed without merging**
