### PR TITLE
Field of record support extensible data type

### PR DESCRIPTION
**Pull request by gfZeng**
Many korma users want korm support JSON data type while the
database is `Postgresql`. [jdbc](https://github.com/clojure/java.jdbc)
provider two protocols for users. I port it to korma.

There is an example:

```clojure
(require '[clojure.java.jdbc :as jdbc]
         '[tools.data.json :as json])

(import '[org.postgresql.util PGobject])

(extend-protocol jdbc/ISQLValue
  clojure.lang.IPersistentMap
  (sql-value [value]
    (doto (PGobject.)
      (.setType "json")
      (.setValue (json/dump-str value))))
  java.util.Date
  (sql-value [value]
    (java.sql.Timestamp. (.getTime value))))

(extend-protocol jdbc/IResultSetReadColumn
  PGobject
  (result-set-read-column [pgobj metadata idx]
    (let [type  (.getType pgobj)
          value (.getValue pgobj)]
      (case type
        "json" (json/load-str value :key-fn keyword)
        :else value))))
```

### CODE REVIEW

**Comment by gfZeng** [comment]
Currently, the `lein test` can not pass. And so I close this `PR`.
I will fix those tests when we thinks it is a good feature.
And then re-open this `PR`

**Comment by immoh** [comment]
Sounds good.

**Comment by gfZeng** [comment]
@immoh 

I think also, `korma` need some plugins. Such as: pagination, DB sharding

**Comment by gfZeng** [comment]
I fixed the tests, And reopen an new [PR](https://github.com/korma/Korma/pull/333)

**Pull request closed without merging**
