### PR TITLE
Restores 0.4.0 behavior where changing the defaults affects existing defdb specs

### PR DESCRIPTION
**Pull request by ls4f**
Took a totally different approach and basically added a function to get options needed for the situation, because it was easiest to merge incomplete defaults.
Also added `*current-db*` check in fns (not sure if needed, but should not hurt).
I'm thinking if it would look better to move `*bound-options*` in `korma.config` and bind it in the `with-db` macro - it will make things a bit shorter, because I won't need `*current-db*` in some of the places.

Assuming it passes all tests, I'll add some tests to cover what the new function is supposed to do exactly.

### CODE REVIEW

**Comment by immoh** [comment]
I think the approach is good, I was thinking about something similar. I think it could be simplified in the the following way (untested):

* in `extract-options`, instead of associng nil value don't assoc the key at all.
* This makes it possible to just `(merge conf-options current-db-options query-options)` to get the options to apply. The values will be overridden if they have been specified.

I'm not sure if I understand the benefit of moving `*bound-options*` to korma.config. Maybe you can implement it in a different commit and see if it simplifies things.

It seems to me that `delimit-str` and `alias-clause` should use `*bound-options*` as it should already contain correct options coalesced.

At minimum we need failing test that this change fixes. It wouldn't hurt to test different combinations of global options, db spec options and query options.

**Comment by ls4f** [comment]
Having missing options in `extract-options` means you get the same effect and have to 'coalesce' with the defaults or you get `nil` references. Seemed shorter to just `(when param (generate param))`. It would mean you don't need the hard-coded options as last resort, but having them enables setting something to `nil` and reverting default behavior (plus it protects against setting null by mistake). 

As for `*bound-options*` - I still think if you set a specific naming, `with-db` should honor it. `korma.config` can't depend on `korma.db`, so it can't coalesce with `*current-db*` unless you pass it as a parameter. Won't save that much code, but having it in the same namespace means you get to hardcode it before `@options`

I'll try to add tests today and take a look if `*bound-options*` is logical some where else.

**Comment by immoh** [comment]
I don't like using nil value as a way to revert to default. If user gives nil we should use nil (obviously it wouldn't work as a naming function).

**Comment by ls4f** [comment]
Well in that case I'll do it with dropping the values - I see no reason why it shouldn't work. Though `nil` is not really a proper delimiter either if you think about it :)

**Comment by ls4f** [comment]
Been looking at why removing keys from the map breaks so many tests  and kinda came to the conclusion that this PR works by the grace of `insert lucky charm here` and 0.4.0 behavior is not so innocent.

My point : 
I've focused on one specific test for the time being - `lein test :only korma.test.core/alias-delimiter-options`.
By the time you get to that point, the parser has already gone through the script and called `mysql` which does `merge-defaults` with a different delimiter (casing also changes but I can't pin the exact sequence for it right now). This is not a problem when you fix the options in the db-spec because `alias-entity` is connected to a specific db and it takes priority over the defaults. When the db-spec is missing the options, however, you are hit a wall, because you have new defaults.
The PR works because it does an empty `merge-defaults` and restores defaults in the mean time.

I'm still thinking about it but so far I see only 2 options : 
1 <=0.4.0 behavior, where the options taken from the current default and you can't really handle multiple databases (at least on queries not using entities)
2 0.4.1 behavior where the db-spec is law and defaults apply only for stuff defined later. Would mean you get to work with different databases, but if you insist on using default config - you have to do it before calling `defdb`

**Comment by immoh** [comment]
Ok, thanks for the update. I'll try to dig into to code during the weekend to see what we can do about it.

**Comment by ls4f** [comment]
So ... I hit my head on the way home and came up with a kind of a middle ground - I still use `*current-db*` but if it is bound to `_default`, I reapply the default options.
If we don`t find another problem with it - I'll add tests and leave it at that.

btw my point about the tests passing by chance because they happen to restore the defaults still stands

**Comment by immoh** [comment]
So here's one solution I came up with:
https://github.com/korma/Korma/commit/dc8631aa99c1e59c58ffd76e7ef5f81b26ceb2f8

I think we should stop changing the default config when defdb is use, it shouldn't be needed if options are merged this way. It could be that somebody is relying on this feature in some weird way but in the long run I would like to get rid of global korma.config options completely. I don't see any use of it as you can set the options on db level and have global default db.

I found out that for example delimit-str is called also when \*bound-options\* is not bound. This basically means there are stlll cases where `with-db` doesn't work correctly. It would be great to get to a point where options can be always read from \*bound-options\* and merging options doesn't have to repeated in many places.

**Comment by ls4f** [comment]
Thought about that, don't remember why I didn't like it.
I did think of one problem with what I did - if someone has by chance specified a db in `defentity` and changed defaults later, the query takes precedence and use the define-time values ... can't imagine who would do that, though.
I am thinking `_default` could be just the `:pool` part so you don`t need the extra destruct and just build the spec.

As for removing defaults - I'm guessing someone out there is lazy and will start getting `nil` references because `*bound-options*` is out of scope. If we're ok with that, most of those`or`/`merges` can be direct usages and no bother with `*current-db*` and `korma.config`. Will probably take a version to fix any missing bindings :)

**Comment by immoh** [comment]
> I did think of one problem with what I did - if someone has by chance specified a db in defentity and changed defaults later, the query takes precedence and it will use the define-time values ... can't imagine who would do that, though. Guessing if someone bothers that much they will be explicit in the db-spec and/or configure early on. Also not sure if it will affect your solution.

It doesn't, the call order doesn't matter in my solution. 

> I am thinking _default could be just the :pool part so you don`t need the extra destruct and just build the spec.

I am not quite sure what you mean by this. Can you elaborate?

> As for removing defaults - I'm guessing someone out there is lazy and will start getting nil references because *bound-options* is out of scope. If we're ok with that, most of thoseor/merges can be direct usages and no bother with *current-db* and korma.config. Will probably take a version to fix any missing bindings :)

I didn't mean we should remove defaults. There should be defaults (the ones currently in korma.config) but they shouldn't be mutable. The only way to change the values would be to create a new db spec and specify which options to override. I think all those values are actually db specific so the global config doesn't make that much sense and only complicates things. We should get nil references only if user specifies nil.

\*bound-options\* should be always bound when functions using it are called. It's a bug waiting to manifest itself, and needs to be addressed in the codebase at some point.

**Comment by ls4f** [comment]
I'm thinking `korma.db/_default` should not contain options - just the `:pool` of what `create-db` returns. I've introduced a function to build a 'current' db-spec from the default + current default options. I figured the options are always complete so I don't need to check other maps.

You do realize if the defaults are immutable you will get 0.4.1 behavior? I don't see a way to implement `set-naming` and so on with purely immutable structures. Doesn't mean I have  problem with it :) I also think setting them globally doesn't make too much sense but the original issue was that my patches 'broke' it. Default behavior is evil and people should be explicit when they want something ... but that's just my view on things.

If things go that way (stable defaults, changed by creating new spec), though - merging a  few maps still won't be necessary since db-spec will always have a complete options map and you can just get it from `*current-db*`.
btw It would also work in the exact same way with no changes to current master, be it a little bloated.

My point about laziness was that if you do something like `(let [stuff (with-db db-spec (some-complex-query))] (prn stuff))`, by the time you get to prn, `*bound-options*` is no longer bound and if `stuff` has lazy sequences you get burned. Using `korma.config/options` catches that case and if the defaults happen to match what you need - you win, otherwise you spend some time pulling your hear out on why the query/result is wrong.

**Comment by immoh** [comment]
> I'm thinking korma.db/_default should not contain options - just the :pool of what create-db returns. 

This is the opposite direction I want to head. Options should be db specific, as I said in the long run I would like to get rid of global mutable options.

> You do realize if the defaults are immutable you will get 0.4.1 behavior? I don't see a way to implement set-naming and so on with purely immutable structures. 

Yes I know it's 0.4.1 behavior but completely without global mutable options. It would be a breaking change (no set-naming et al.) and therefore I don't want to introduce it now in order to fix this, it would be for 0.5.0.

> If things go that way (stable defaults, changed by creating new spec), though - merging a few maps still won't be necessary since db-spec will always have a complete options map and you can just get it from *current-db*.

Good point. It would really simplify things a lot.

> My point about laziness was that if you do something like (let [stuff (with-db db-spec (some-complex-query))] (prn stuff)), by the time you get to prn, *bound-options* is no longer bound and if stuff has lazy sequences you get burned. Using korma.config/options catches that case and if the defaults happen to match what you need - you win, otherwise you spend some time pulling your hear out on why the query/result is wrong.

Yeah, if the defaults happen to match what you need. This means there will always be cases when it doesn't work and the codebase just get bloated when we try to patch it.

I'm starting to think that the best way to resolve this would be to revert commits that caused this (with-db fixes) and release it as 0.4.2. Then we could first remove the global config, fix with-db issues and release it later as 0.5.0 since it would be a breaking change. Thoughts?

**Comment by ls4f** [comment]
Well the last patch you suggested here does come pretty close to 0.4.0 so I'm don't think there is need to revert the naming patches but it is up to you - my code has been adjusted to work with korma for now so it won't break either way. Can't really say I am big on going back but having 'sorta fixed' code isn't all that better. 

0.5.0 sounds like a good idea and as long as it has breaking changes - I think korma should follow the JDBC example and remove dynamic variables entirely in order to prevent future laziness/threading issues.

btw Korma spacing is terribly inconsistent. Any chance you can pass everything through auto-indent and have a commit just for that? Making a PR is a pain in the rear when emacs goes and fixes half the code:)

**Comment by immoh** [comment]
Thanks for your help.  

Decided to revert #284 and #293, and pushed 0.4.2 out. I think we really need to get rid of `korma.config/options` before this can properly fixed.

Re: spacing, do you mean spaces vs. tabs, or Clojure formatting? I haven't had any issues. I'm willing to merge commits that improve this, also part of other PRs, as long as whitespace changes and actual code changes are in separate commits.

**Comment by ls4f** [comment]
Good t finally have a solution (as opposed to being kind of midway). I did spot spaces in the code (including tests) that break after removing `korma/config/options` but if I get the time I'll try to make a PR towards removing it.

I mean indentation, including within comments. Sometimes I would change one line and Emacs would literally align half the file. I don't mind changing settings but there are cases when two consecutive functions differ by a space or two. A PR on that is easier and I'll try to get to it these days.

**Comment by immoh** [comment]
PR much appreciated. It would  probably make sense to try to get rid of unnecessary dynamic vars (like \*bound-options\*) first.

**Pull request closed without merging**
