### PR TITLE
Adds the ability to specify limit and offset options on union, union-all, and intersect.  Adds the ability to alias joins against subselects

### PR DESCRIPTION
**Pull request by ejschoen**
This is based on the released 0.4.2 branch.  I needed limit on union, so modified the engine code to invoke the `sql-limit-offset` code for union, union-all, and intersect.

I also needed joins of the form:

``` sql
 (select .. from table1 join (select table2 where ...) as alias on table1.foo=alias.bar.`   
```

This commit adds the ability to use a subselect in a join, in a 2-vector, like for field and table aliases:

``` clojure
(select table1 (join :left [(subselect table2 (where {... })) alias] 
                     (= :table1.foo :alias.bar)))
```

### CODE REVIEW

**Comment by ghost** [comment]
@ejschoen There are "prod" credentials in this PR files.

**Comment by ghost** [comment]
Everything's still here oh my god !!

**Comment by ejschoen** [comment]
Yeah, they leaked in.  Thanks.

**Comment by ghost** [comment]
Nothing to see here

**Pull request closed without merging**
