### PR TITLE
supprot predicate keyword

### PR DESCRIPTION
**Pull request by zjhmale**
i wonder if we can use both keyword and symbol to present predicates, this is really useful when we construct queries with predicate in a macro, make the code more readable.

### CODE REVIEW

**Comment by zjhmale** [comment]
@immoh @ibdknox @AlexBaranosky

**Comment by immoh** [comment]
This looks useful. Maybe the implementation could be simplified so that we have both symbols and keywords in one map and there wouldn't be need to check two maps?

**Comment by zjhmale** [comment]
ok, that sounds cool, let me fix it.

**Comment by zjhmale** [comment]
done @immoh

**Comment by immoh** [comment]
Please squash the commits into a single one and I'll merge this.

**Comment by zjhmale** [comment]
ok, just a minute.

**Comment by zjhmale** [comment]
done. @immoh

**Comment by immoh** [comment]
Thanks!

**Comment by zjhmale** [comment]
my pleasure :)

**Pull request merged**
